package Task2Tests;

import lab11.Task2.BirthdayMailStrategy;
import lab11.Task2.Client;
import lab11.Task2.GiftMailStrategy;
import lab11.Task2.MailBox;
import lab11.Task2.MailCode;
import lab11.Task2.MailInfo;
import lab11.Task2.MailJetService;
import lab11.Task2.MailSender;
import lab11.Task2.MailStrategy;
import lab11.Task2.Sex;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class MailServiceTest {

    static class FakeMailJetService extends MailJetService {

        static class SentEmail {
            final String toEmail;
            final String toName;
            final String subject;
            final String body;

            SentEmail(String toEmail, String toName, String subject, String body) {
                this.toEmail = toEmail;
                this.toName = toName;
                this.subject = subject;
                this.body = body;
            }
        }

        private final List<SentEmail> sentEmails = new ArrayList<>();

        FakeMailJetService() {
            super("test_public_key", "test_private_key",
                    "from@example.com", "Test Sender");
        }

        @Override
        public void send(String toEmail, String toName,
                         String subject, String htmlBody) {
            sentEmails.add(new SentEmail(toEmail, toName, subject, htmlBody));
        }

        List<SentEmail> getSentEmails() {
            return sentEmails;
        }
    }

    @Test
    void birthdayMailStrategyUsesClientNameInSubjectAndBody() {
        Client client = new Client("Daryna", 20, Sex.FEMALE, "daryna@example.com");
        MailStrategy strategy = new BirthdayMailStrategy();

        String subject = strategy.generateSubject(client);
        String body = strategy.generateBody(client);

        assertEquals("Happy Birthday, Daryna!", subject);
        assertTrue(body.contains("Dear Daryna"), "Body should contain greeting with name");
    }

    @Test
    void giftMailStrategyUsesClientNameInSubjectAndBody() {
        Client client = new Client("Arsenii", 13, Sex.MALE, "arsenii@example.com");
        MailStrategy strategy = new GiftMailStrategy();

        String subject = strategy.generateSubject(client);
        String body = strategy.generateBody(client);

        assertEquals("A special gift just for you!", subject);
        assertTrue(body.contains("Hello Arsenii"), "Body should contain greeting with name");
        assertTrue(body.toLowerCase().contains("gift"),
                "Body should mention gift");
    }

    @Test
    void clientIdsShouldBeAutoIncremented() {
        Client c1 = new Client("A", 18, Sex.FEMALE, "a@example.com");
        Client c2 = new Client("B", 19, Sex.MALE, "b@example.com");

        assertEquals(c1.getId() + 1, c2.getId());
    }

    @Test
    void mailSenderShouldPickCorrectStrategyAndCallMailJetService() {
        FakeMailJetService fakeService = new FakeMailJetService();
        MailSender sender = new MailSender(fakeService);

        Client client = new Client("Daryna", 20, Sex.FEMALE, "daryna@example.com");
        MailInfo info = new MailInfo(client, MailCode.BIRTHDAY);

        sender.sendMail(info);

        List<FakeMailJetService.SentEmail> sent = fakeService.getSentEmails();
        assertEquals(1, sent.size(), "Exactly one email should be sent");

        FakeMailJetService.SentEmail email = sent.get(0);
        assertEquals("daryna@example.com", email.toEmail);
        assertEquals("Daryna", email.toName);
        assertTrue(email.subject.startsWith("Happy Birthday"),
                "Subject should be generated by BirthdayMailStrategy");
        assertTrue(email.body.contains("Daryna"),
                "Body should contain client name converted to HTML");
    }

    @Test
    void mailBoxSendAllShouldSendAllInfosAndClearQueue() {
        FakeMailJetService fakeService = new FakeMailJetService();
        MailSender sender = new MailSender(fakeService);
        MailBox mailBox = new MailBox(sender);

        Client c1 = new Client("User1", 25, Sex.MALE, "u1@example.com");
        Client c2 = new Client("User2", 17, Sex.FEMALE, "u2@example.com");

        mailBox.addMailInfo(new MailInfo(c1, MailCode.BIRTHDAY));
        mailBox.addMailInfo(new MailInfo(c2, MailCode.GIFT));

        mailBox.sendAll();

        List<FakeMailJetService.SentEmail> sent = fakeService.getSentEmails();
        assertEquals(2, sent.size(), "Two emails should be sent");

        mailBox.sendAll();
        assertEquals(2, sent.size(), "Queue should be cleared after sendAll");
    }
}
